apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["https","http"]
    InsecureSkipVerify = true
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [retry]
    [acme]
    email = "masmax@mail.ru"
    storageFile = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    onDemand = true
    acmeLogging = true
    [acme.httpChallenge]
    entryPoint = "http"
